services:
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-revelo_production}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-revelo_production}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - revelo_network

  migrate:
    image: ghcr.io/jancernik/revelo-api:${GIT_COMMIT_HASH:-latest}
    command: ["node", "src/database/migrate.js", "production"]
    environment:
      VERIFY_ENV: "false"
      NODE_ENV: production
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD?}
      DB_NAME: ${DB_NAME:-revelo_production}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
    deploy:
      mode: replicated-job
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
    networks:
      - revelo_network

  ai:
    image: ghcr.io/jancernik/revelo-ai:${GIT_COMMIT_HASH:-latest}
    environment:
      AI_PORT: ${AI_PORT:-8000}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${AI_PORT:-8000}/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - ai_data:/app/models
    networks:
      - revelo_network

  api:
    image: ghcr.io/jancernik/revelo-api:${GIT_COMMIT_HASH:-latest}
    environment:
      VERIFY_ENV: "true"
      NODE_ENV: production
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD?}
      DB_NAME: ${DB_NAME:-revelo_production}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      JWT_SECRET: ${JWT_SECRET?}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET?}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL?}
      AI_BASE_URL: http://ai:${AI_PORT:-8000}
      API_PORT: ${API_PORT:-3000}
      SMTP_HOST: ${SMTP_HOST?}
      SMTP_PORT: ${SMTP_PORT?}
      SMTP_USER: ${SMTP_USER?}
      SMTP_PASS: ${SMTP_PASS?}
      SMTP_EMAIL: ${SMTP_EMAIL?}
      UPLOADS_DIR: ${UPLOADS_DIR:-uploads}
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      BUCKET_ENDPOINT: ${BUCKET_ENDPOINT}
      BUCKET_ACCESS_KEY_ID: ${BUCKET_ACCESS_KEY_ID}
      BUCKET_SECRET_ACCESS_KEY: ${BUCKET_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      BUCKET_REGION: ${BUCKET_REGION:-auto}
      BUCKET_PUBLIC_URL: ${BUCKET_PUBLIC_URL}
    volumes:
      - uploads:/app/${UPLOADS_DIR:-uploads}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT:-3000}/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - revelo_network

  client:
    image: ghcr.io/jancernik/revelo-client:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 20s
        max_failure_ratio: 0.3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - revelo_network

  nginx:
    image: nginx:alpine
    environment:
      API_PORT: ${API_PORT:-3000}
      NGINX_PORT: ${NGINX_PORT:-80}
    ports:
      - target: 80
        published: ${NGINX_PORT:-80}
        protocol: tcp
        mode: ingress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - uploads:/var/www/uploads:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 20s
        max_failure_ratio: 0.3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${NGINX_PORT:-80}/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - revelo_network

volumes:
  postgres_data:
    driver: local
  ai_data:
    driver: local
  uploads:
    driver: local

networks:
  revelo_network:
    driver: overlay
    attachable: true
